-- lichen — generated by `bun run build`, do not edit

local M = {}

---@class lichen.config
---@field transparent? boolean  -- keep the terminal's background instead of base
M.config = { transparent = false }

---@param opts? lichen.config
function M.setup(opts)
  M.config = vim.tbl_deep_extend("force", M.config, opts or {})
end

function M.load()
  if vim.g.colors_name then
    vim.cmd("hi clear")
  end
  vim.o.termguicolors = true
  vim.o.background = "dark"
  vim.g.colors_name = "lichen"

  local palette = require("lichen.palette")
  local groups = require("lichen.groups")

  if M.config.transparent then
    for _, name in ipairs({ "Normal", "NormalNC", "SignColumn", "LineNr", "EndOfBuffer" }) do
      local g = groups[name]
      if type(g) == "table" and g.bg then
        g.bg = "NONE"
      end
    end
  end

  for name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, name, spec)
  end

  for i, hex in ipairs(palette.ansi) do
    vim.g["terminal_color_" .. (i - 1)] = hex
  end
end

return M
