-- lichen — generated by `bun run build`, do not edit

---@class lichen.palette
local M = {
  ["base"] = "#040404",
  ["surface"] = "#0f0f0f",
  ["overlay"] = "#1d1d1d",
  ["border"] = "#303030",
  ["muted"] = "#6c6c6c",
  ["subtle"] = "#9b9b9b",
  ["text"] = "#cecece",
  ["bright"] = "#f5f5f5",
  ["accent"] = "#d4fd80",
  ["accent-quiet"] = "#b4c695",
  ["on-accent"] = "#0a0a0a",
  ["error"] = "#e47b79",
  ["error-bright"] = "#ff9492",
  ["warning"] = "#e1b767",
  ["warning-bright"] = "#f5ca7a",
  ["blue-tint"] = "#919cae",
  ["blue-tint-bright"] = "#c3cfe2",
  ["magenta-tint"] = "#a795a4",
  ["magenta-tint-bright"] = "#dac7d7",
  ["cyan-tint"] = "#86a1a3",
  ["cyan-tint-bright"] = "#b8d4d5",
  diff = {
    added = "#131410",
    deleted = "#1b1110",
    changed = "#17130d",
  },
  ansi = { "#0f0f0f", "#e47b79", "#b4c695", "#e1b767", "#919cae", "#a795a4", "#86a1a3", "#cecece", "#6c6c6c", "#ff9492", "#d4fd80", "#f5ca7a", "#c3cfe2", "#dac7d7", "#b8d4d5", "#f5f5f5" },
}

return M
