  # lichen — generated by `bun run build`, do not edit
  local grey='#6c6c6c'
  local red='#e47b79'
  local yellow='#e1b767'
  local blue='#cecece'
  local magenta='#d4fd80'
  local cyan='#b4c695'
  local white='#f5f5f5'
