import type { Lichen } from "../palette";
import type { Emitter } from "./types";

export const ghostty: Emitter = {
  path: "ports/ghostty/lichen",
  render(p: Lichen): string {
    const paletteLines = p.ansi.map((hex, i) => `palette = ${i}=${hex}`).join("\n");
    return [
      "# lichen — generated by `bun run build`, do not edit",
      paletteLines,
      `background = ${p.hex("base")}`,
      `foreground = ${p.hex("text")}`,
      `cursor-color = ${p.hex("accent")}`,
      `cursor-text = ${p.hex("on-accent")}`,
      `selection-background = ${p.hex("overlay")}`,
      `selection-foreground = ${p.hex("text")}`,
      "",
    ].join("\n");
  },
};
