import { expect, test } from "bun:test";
import { lichen } from "../palette";
import { ghostty } from "./ghostty";

// this exact string is the independent expected value from spec-06.md.
const EXPECTED = `# lichen — generated by \`bun run build\`, do not edit
palette = 0=#0f0f0f
palette = 1=#e47b79
palette = 2=#b4c695
palette = 3=#e1b767
palette = 4=#919cae
palette = 5=#a795a4
palette = 6=#86a1a3
palette = 7=#cecece
palette = 8=#6c6c6c
palette = 9=#ff9492
palette = 10=#d4fd80
palette = 11=#f5ca7a
palette = 12=#c3cfe2
palette = 13=#dac7d7
palette = 14=#b8d4d5
palette = 15=#f5f5f5
background = #040404
foreground = #cecece
cursor-color = #d4fd80
cursor-text = #0a0a0a
selection-background = #1d1d1d
selection-foreground = #cecece
`;

test("ghostty.render(lichen) equals the exact expected output", () => {
  expect(ghostty.render(lichen)).toBe(EXPECTED);
});

test("ghostty.path is ports/ghostty/lichen", () => {
  expect(ghostty.path).toBe("ports/ghostty/lichen");
});
