import type { Emitter } from "./types";

/** herdr has no external theme files: follow the terminal palette, override the ui tokens. */
export const herdr: Emitter = {
  path: "ports/herdr/lichen.toml",
  render(p) {
    return [
      "# lichen — generated by `bun run build`, do not edit",
      "# paste over the [theme] section of ~/.config/herdr/config.toml",
      "[theme]",
      'name = "terminal"',
      "",
      "[theme.custom]",
      `sidebar_bg = "${p.hex("surface")}"`,
      `active_row_bg = "${p.hex("overlay")}"`,
      `selection_bg = "${p.hex("border")}"`,
      'panel_bg = "reset"',
      `accent = "${p.hex("accent")}"`,
      `green = "${p.hex("accent-quiet")}"`,
      `blue = "${p.hex("blue-tint")}"`,
      `red = "${p.hex("error")}"`,
      `yellow = "${p.hex("warning")}"`,
      "",
    ].join("\n");
  },
};
