import type { Emitter } from "./types";

/**
 * the colour locals p10k's lean style reads. replaces the block near line 41 of ~/.p10k.zsh.
 * grey → muted, blue (dir) → text, magenta (prompt char) → accent, cyan → accent-quiet,
 * white → bright, red/yellow → error/warning.
 */
export const p10k: Emitter = {
  path: "ports/p10k/lichen.zsh",
  render(p) {
    return [
      "  # lichen — generated by `bun run build`, do not edit",
      `  local grey='${p.hex("muted")}'`,
      `  local red='${p.hex("error")}'`,
      `  local yellow='${p.hex("warning")}'`,
      `  local blue='${p.hex("text")}'`,
      `  local magenta='${p.hex("accent")}'`,
      `  local cyan='${p.hex("accent-quiet")}'`,
      `  local white='${p.hex("bright")}'`,
      "",
    ].join("\n");
  },
};
